typedef struct NO* ArvLLRB;
ArvLLRB* criar_arvore();
void liberar_arvore(ArvLLRB* raiz);
int inserir_novo_no(ArvLLRB* raiz,int valor);
int remover_no_arvore(ArvLLRB *raiz, int valor);
int verifica_arvore_vazia(ArvLLRB *raiz);
int total_nos_arvore(ArvLLRB *raiz);
int altura_arvore(ArvLLRB *raiz);
int buscar_na_arvore(ArvLLRB *raiz, int valor);
void percorrer_pre_ordem(ArvLLRB *raiz, int H);
void percorrer_em_ordem(ArvLLRB *raiz, int H);
void percorrer_pos_ordem(ArvLLRB *raiz, int H);